### PR TITLE
Use dplR::latexify to translate names to latex

### LINKED ISSUE #102: RefManageR::ReadBib and RefManageR::WriteBib changes Ois{\'i}n to Ois{\a'\i}n
RefManageR::ReadBib and RefManageR::WriteBib changes `Ois{\'i}n` to `Ois{\a'\i}n` in

```
@Article{Ryan-Hamaker-2021,
  author = {Ois{\'i}n Ryan and Ellen L. Hamaker},
  date = {2021-06},
  journaltitle = {Psychometrika},
  title = {Time to intervene: A continuous-time approach to network analysis and centrality},
  doi = {10.1007/s11336-021-09767-0},
  number = {1},
  pages = {214--252},
  volume = {87},
  publisher = {Springer Science and Business Media {LLC}},
}
```

is there a way to prevent this from happening? I would appreciate some guidance on this issue.

### PR DESCRIPTION
**Pull request by mwmclean**
* Switch from tools::encoded_text_to_latex to dplR::latexify in
* toBiblatex and toBibtex to fix translation of accented i characters to latex
* Fixes #102, #106

### CODE REVIEW

**Comment by kijinosu** [comment]
Writing BibLatex to file then reading it gets errors.

This is with #109.

```
bib <- c(BibEntry(bibtype = "article", 
		key = "shiotsuki2011kasai", 
		title = "葛西賢太著,『現代瞑想論-変性意識がひらく世界-』",
		author = "塩亮子 and 葛西賢太", 
		journal = "宗教と社会",
		volume = 17,
		pages = "67--69",
		year = 2011, 
		publisher = "「宗教と社会」学会"),
		BibEntry(bibtype = "article", 
		key = "hiromitsu2022altered", 
		title = "意識状態の変容と脳内ネットワーク",
		author = "弘光健太郎 and ヒロミツケンタロウ", 
		journal = "鶴見大学仏教文化研究所紀要",
		volume = 27,
		pages = "53--66",
		year = 2022, 
		publisher = "鶴見大学"),
		BibEntry(bibtype = "article",
		key = "galante2024altered",
  		title="Altered states of consciousness caused by a mindfulness-based programme up to a year later: Results from a randomised controlled trial",
  		author="Galante, Julieta and Jesús Montero-Marín and Maris Vainre and Géraldine Dufour and Javier García-Campayo and Peter B. Jones",
  		journal="Plos one",
  		volume=19,
 		number=7,
  		pages="e0305928",
  		year=2024,
  		publisher="Public Library of Science San Francisco, CA USA")
		)

tmpfile <- tempfile(pattern = "bib109", tmpdir = tempdir(), fileext = ".bib")
WriteBib(bib, file=tmpfile, biblatex = TRUE)
bib109 <- ReadBib(tmpfile)
```

Results:

```
Ignoring entry ‘shiotsuki2011kasai’ (line1) because: 
        The name list field author cannot be parsed

Ignoring entry ‘hiromitsu2022altered’ (line11) because: 
        The name list field author cannot be parsed

警告メッセージ:
1: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
  unable to translate '塩亮子\<ff>' to a wide string
2: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
  input string 1 is invalid
3: grepl("^[[:space:]]*$", x) で:
  unable to translate '塩亮子\<ff>' to a wide string
4: grepl("^[[:space:]]*$", x) で: input string 1 is invalid
5: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
  unable to translate '弘光健太郎\<ff>' to a wide string
6: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
  input string 1 is invalid
7: grepl("^[[:space:]]*$", x) で:
  unable to translate '弘光健太郎\<ff>' to a wide string
8: grepl("^[[:space:]]*$", x) で: input string 1 is invalid
```

**Comment by kijinosu** [comment]
Here is an example from biblatexExamples.bib using #109:

```
examplepath <- file.path(system.file(package="RefManageR"),"Bib","biblatexExamples.bib")
bibexamples <- ReadBib(examplepath)

iliad <- toBiblatex(bibexamples["iliad"])
writeLines(iliad)
# @Book{iliad,
#   author = {\{Homer\}},
#   title = {Die Ilias},
#   date = {2004},
#   translator = {Wolfgang Schadewaldt},
#   introduction = {Joachim Latacz},
#   edition = {3},
#   publisher = {Artemis \& Winkler},
#   location = {D{\"u}sseldorf and Z{\"u}rich},
#   langid = {german},
#   sorttitle = {Ilias},
#   indextitle = {Ilias, Die},
#   shorttitle = {Ilias},
#   annotation = {A German translation of the \emph{Iliad}. Note the
#                   \texttt{translator} and \texttt{introduction} fields and the
#                   format of the \texttt{location} field in the database
#                   file. Also note the \texttt{sorttitle} and \texttt{indextitle}
#                   fields},
# }
tmpfile <- tempfile(pattern = "bib109", tmpdir = tempdir(), fileext = ".bib")
WriteBib(bibexamples["iliad"], file=tmpfile, biblatex = TRUE)
bib109 <- ReadBib(tmpfile)
# Ignoring entry ‘iliad’ (line1) because: 
#         The name list field author cannot be parsed
# 
# 警告メッセージ:
# 1: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
#   unable to translate 'Homer\<ff>' to a wide string
# 2: grepl("\\\\[[:punct:]]", x, useBytes = FALSE) で:
#   input string 1 is invalid
# 3: grepl("^[[:space:]]*$", x) で:
#   unable to translate 'Homer\<ff>' to a wide string
# 4: grepl("^[[:space:]]*$", x) で: input string 1 is invalid
```

**Comment by kijinosu** [comment]
Note that this affects corporate authors enclosed in braces.

```
@book{CUDA, 
   author = {{NVIDIA Corporation}}, 
   title = {NVIDIA CUDA Compute Unified Device Architecture Programming Guide}, 
   publisher = {NVIDIA Corporation}, 
   year = {2007}
}
```

https://tex.stackexchange.com/questions/10808/using-a-corporate-author-in-the-author-field-of-a-bibliographic-entry-spell

**Comment by mwmclean** [comment]
@kijinosu thanks for your report. Addressed by my last commit if you'd like to pull and reinstall.

**Comment by kijinosu** [comment]
Note that this affects corporate authors enclosed in braces.

```
@book{CUDA, 
   author = {{NVIDIA Corporation}}, 
   title = {NVIDIA CUDA Compute Unified Device Architecture Programming Guide}, 
   publisher = {NVIDIA Corporation}, 
   year = {2007}
}
```

https://tex.stackexchange.com/questions/10808/using-a-corporate-author-in-the-author-field-of-a-bibliographic-entry-spell

> @kijinosu thanks for your report. Addressed by my last commit if you'd like to pull and reinstall.

This works very nicely. Thank you for working on it.

**Pull request closed without merging**
